version: 1.0.{build}
image:
- Visual Studio 2017
clone_depth: 1

artifacts:
- path: ml_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

before_build:
    - cmd: ren "C:\Program Files (x86)\Windows Kits\10\include\00wdf" "wdf"

build_script:
- cmd: >-

    build\buildscript.bat

    build\test.bat

after_build:
- cmd: >-
    build\package.bat

deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
