version: 1.0.{build}
image:
- Visual Studio 2017
clone_depth: 1

init:
- cmd: 
environment:
  matrix:
  - BITS: 64
  - BITS: 32
install:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"
    mkdir %APPVEYOR_BUILD_FOLDER%\win\w%BITS%
    appveyor-retry appveyor DownloadFile https://github.com/KxSystems/kdb/raw/master/w%BITS%/q.lib -FileName %APPVEYOR_BUILD_FOLDER%\win\w%BITS%\q.lib

artifacts:
- path: ml_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

build_script:
- cmd: >-

    build\buildscript.bat

    build\test.bat

after_build:
- cmd: >-
    build\package.bat

deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
